language: dart
dart:
  - stable
  - beta
  - dev
  - test
  - "1.15.0"
  - "beta/release/2.9.0-2.0.beta"
  - "dev/release/2.9.0-2.0.dev"
  - dartanalyzer: --fatal-warnings lib

install:
  # https://flutter.dev/docs/get-started/web
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov

script:
  - ./flutter/bin/flutter test --coverage

after_success:
  - coveralls-lcov coverage/lcov.info

# Deploy configuration
# Use the Flutter console to configure your web app. 
# https://docs.travis-ci.com/user/deployment/firebase/
deploy:
  provider: firebase
  project: "e4app"
  skip_cleanup: true

cache:
  directories:
    - $HOME/.pub-cache
