version: 2.1

#orbs:
 # codecov: codecov/codecov@1.0.2
  
jobs:
 # build:
  #  steps:
   #   - codecov/upload:
    #      file:
          
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install sqlite3 libsqlite3-dev
      - run: flutter doctor
      - run: 
          command: flutter test
          name: Run Unit Test
    #  - run: flutter analyze
    #  - run: flutter -v build apk
    
