version: 2.1

# Orb declarations
orbs:
  codecov: codecov/codecov@1.0.2

executors:
  default-executor:
    docker:
      - image: cirrusci/flutter:stable

commands:
  tests:
    description: "Run local unit tests"
    steps:
      - run:
          name: Setup Environment Variables
          command: echo "export PATH="$PATH":"$HOME/.pub-cache/bin"" >> $BASH_ENV
      - run:
          name: command to run unit tests
          command: flutter test --reporter json | tojunit --output test-results/dart-tests/device_widgets_unit_tests-report.xml
  run-test-coverage:
    description: "Run all tests"
    steps:
      - run:
          name: command to run all tests
          command: flutter test --coverage
      - codecov/upload:
          file: coverage/lcov.info

  dependencies:
    description: "Download dependencies and setup global packages"
    steps:
      - checkout
      - run:
          name: Download deps
          shell: << parameters.shell >>
          command: flutter clean && flutter pub get

  flutter-tests:
    description: "Run flutter tests"
    steps:
      - run:
          name: command to run flutter tests
          command: |
            flutter test --coverage
      - codecov/upload:
          file: coverage/lcov.info
jobs:
  build:
    executor: default-executor
    steps:
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
      - tests
      - run-test-coverage
      - store_test_results:
          path: test-results

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
  test-changelog-tag:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      
