version: 2.1
orbs:
  flutter: circleci/flutter@1.2.0
workflows:
  test:
    jobs:
      - flutter/unit_test:
          version: 2.2.3
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install sqlite3 libsqlite3-dev
      - run: flutter doctor
      - run: 
          command: flutter test
          name: Run Unit Test
    #  - run: flutter analyze
    #  - run: flutter -v build apk
