version: 2.1

# Orb declarations --
orbs:
  codecov: codecov/codecov@3.0.0
  
jobs:     
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - codecov/upload:
          token: CODECOV_TOKEN

      - run: 
          command: sudo apt-get update
          name: Downloading latest version of my app
          
      - run: 
          command: flutter doctor
          name: Checking the environment
      
      - run: 
          command: flutter pub get
          name: Getting all dependencies
      
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
      
      - run: 
          command: flutter test --coverage
          name: Run Unit Test
          
      - run: 
          command: flutter test --coverage
          name: Run Test coverage
      - store_test_results:
          path: test-results
       
      - run:
        name: Download and validate Codecov script
        command: |
          curl -fLso codecov https://codecov.io/bash;
          VERSION=$(grep -o 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
          for i in 1 256 512
          do
            shasum -a $i -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM")
          done
  - run:
      name: Upload coverage reports to Codecov
      command: bash ./codecov

      - checkout
      - codecov/upload:
          token: CODECOV_TOKEN
          file: coverage/lcov.info
          

workflows:
  build:
    jobs:
      - build
      
      

