version: 2.1

# Orb declarations --
orbs:
  codecov: codecov/codecov@1.0.2
  
jobs:     
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout

      - run: 
          command: sudo apt-get update
          name: Downloading latest version of my app
          
      - run: 
          command: flutter doctor
          name: Checking the environment
      
      - run: 
          command: flutter pub get
          name: Getting all dependencies
      
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
      
      - run: 
          command: flutter test --coverage
          name: Run Unit Test
          
      - run: 
          command: flutter test --coverage
          name: Run Test coverage
          
#      - name: Upload coverage reports to Codecov
 #         run: |
  #        curl -Os https://uploader.codecov.io/latest/linux/codecov 
   #       chmod +x codecov 
    #      ./codecov
     # - run:
      #    command: apt install gpg-agent
       #   name: Adding gpg agent
          
      - store_test_results:
          path: test-results

      - codecov/upload:
         file: coverage/lcov.info
