version: 2.1

# Orb declarations --
orbs:
  codecov: codecov/codecov@3.0.0
  
jobs:     
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      #- codecov/upload:
          #token: b722080d-1dac-4599-9f09-1c51abda0182 

      - run: 
          command: sudo apt-get update
          name: Downloading latest version of my app
          
      - run: 
          command: flutter doctor
          name: Checking the environment
      
      - run: 
          command: flutter pub get
          name: Getting all dependencies
      
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
      
      - run: 
          command: flutter test --coverage
          name: Run Unit Test
          
      - run: 
          command: flutter test --coverage
          name: Run Test coverage
      - store_test_results:
          path: test-results

      - codecov/upload:
          #token: b722080d-1dac-4599-9f09-1c51abda0182 
          file: coverage/lcov.info
          

workflows:
  build:
    jobs:
      - build
      
      

