version: 2.1

# Orb declarations
orbs:
  codecov: codecov/codecov@1.0.2
  
jobs:
   #   - codecov/upload:
    #      file:
          
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: 
          command: sudo apt-get update
          name: Downloading latest version of my app
      - run: 
          command: flutter doctor
          name: Checking the environment
      - run: 
          command: flutter pub get
          name: Getting all dependencies
      - run: 
          command: flutter test --coverage
          name: Run Unit Test

      - codecov/upload:
         file: coverage/lcov.info
